cargo-features = ["codegen-backend"]

[package]
name = "crabvm"
version = "0.0.1"
edition = "2021"

[dependencies]

[profile.dev]
codegen-backend = "cranelift"

[profile.release]
lto = true
codegen-units = 1
